refactor(husky): add condition for practice folder

diff --git a/furniture-ecommerce/.husky/pre-push b/furniture-ecommerce/.husky/pre-push
--- a/furniture-ecommerce/.husky/pre-push
+++ b/furniture-ecommerce/.husky/pre-push
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-cd furniture-ecommerce
+cd furniture-ecommerce|| { echo "❌ Cannot find furniture-ecommerce directory"; exit 1; }
 
 echo "📘 Type checking..."
 pnpm type-check
